sudo: required
services:
  - docker

before_install:
  - docker build -t rayudubk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rayudubk/react-test npm test -- --coverage

after_success:
  - docker build -t rayudubk/multi-client ./client
  - docker build -t rayudubk/multi-nginx ./nginx
  - docker build -t rayudubk/multi-server ./server
  - docker build -t rayudubk/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rayudubk/multi-client
  - docker push rayudubk/multi-nginx
  - docker push rayudubk/multi-server
  - docker push rayudubk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucketname: 'elasticbeanstalk-us-east-1-214934986569'
  bucketpath: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
